# Generated by Django 5.2.7 on 2025-10-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tarefa_prioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('A fazer', 'A fazer'), ('Fazendo', 'Fazendo'), ('Pronto', 'Pronto')], default='P', max_length=7),
        ),
    ]
